# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19p_q6lZ-UdoPFxkswuC4mrjs9AOeVXKF
"""

#Task 1
    #- Create a function that updates a dictionary (dct) with a new key-value pair.
    #- If the key already exists in dct, print the original value, then update its value.
    #- Return the updated dictionary.

#Answers:
def update_dict(dct, key, value):
    if not isinstance(dct, dict):
        raise ValueError("The provided input must be a dictionary.")

    if key in dct:                          # Check if key exists; if so, print its current value.
        print("Original value:", dct[key])

    dct[key] = value                        # Update the dictionary with the new key-value pair.
    return dct

def update_dictionary(dct, key, value):


    return

# Task 2
# Invoke the function "update_dictionary" using the following scenarios:
# - {}, "name", "Alice"
# - {"age": 25}, "age", 26

#Answers:
def update_dictionary(dct, key, value):
    if not isinstance(dct, dict):
        raise ValueError("Input must be a dictionary.")

    if key in dct:                        #If the key already exists, print the original value
        print("Original value:", dct[key])

    dct[key] = value                      #Update the dictionary with the new key-value pair
    return dct

# Scenario 1: Updating an empty dictionary with key "name" and value "Alice"
result1 = update_dictionary({}, "name", "Alice")
print("Scenario 1 result:", result1)
# Expected output: {'name': 'Alice'}

# Scenario 2: Updating an existing key "age" in the dictionary {"age": 25} to 26
result2 = update_dictionary({"age": 25}, "age", 26)
# Expected to print: Original value: 25, then output: {'age': 26}
print("Scenario 2 result:", result2)