# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIU_RgK4dRNa0Fg0Ff88xpyt3weO45Jf
"""

#Task 1
    #- Create a function that reverses a given string (s).
    #- s must be a string.
    #- Return the reversed string.

#Answers:
def reverse_string(s):
    if not isinstance(s, str):    #Type Check: Function first verifies that the input s is a string, raising a ValueError if it is not.
        raise ValueError("Input must be a string.")
    return s[::-1]                #Reversal Technique: Python’s slicing method s[::-1] to reverse the string. Reversed string is then returned.

# Task 2
# Invoke the function "string_reverse" using the following scenarios:
# - "Hello World"
# - "Python"

#Answers:
def string_reverse(s):          #Type Check: Function first verifies that the input s is a string, raising a ValueError if it is not.
    if not isinstance(s, str):
        raise ValueError("Input must be a string.")
    return s[::-1]              #Reversal Technique: Python’s slicing method s[::-1] to reverse the string. Reversed string is then returned.

#Scenario 1:
result1 = string_reverse("Hello World")
print("#Scenario 1 - String 'Hello World' Reversed:", result1)  #Reversal Technique: Python’s slicing method s[::-1] to reverse the string. Expected output: "dlroW olleH"

#Scenario 2:
result2 = string_reverse("Python")
print("#Scenario 2 - String 'Python' Reversed:", result2)       #Reversal Technique: Python’s slicing method s[::-1] to reverse the string. Expected output: "nohtyP"

