# -*- coding: utf-8 -*-
"""q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7t79wNp8IQcNHQ9FWva2q74gD_Us7yx
"""

#Task 1
   # - Define a class named Car with attributes: make, model, year
   # - Initialize these attributes in the __init__ method
   # - Add a method named describe_car() that prints information about the car as "Year Make Model"

#Answers:
class Car:                                              #Class Definition: The Car class is defined with an __init__ method that
    def __init__(self, make, model, year):              #initializes the Car object with the attributes make, model, and year.

        self.make = make                                #Attributes Initialization: In the __init__ method, the parameters make, model, and year are assigned to the
        self.model = model                              #instance attributes self.make, self.model, and self.year, respectively.
        self.year = year                                #parameter make: The manufacturer of the car (e.g., 'BYD').
                                                        #paramerter model: The model of the car (e.g., 'Denzel 9').
                                                        #parameter year: The year the car was manufactured (e.g., 2024).

    def describe_car(self):                             #Method describe_car: This method prints the car's details in the format "Year Make Model" using an f-string for formatting.​
        print(f"{self.year} {self.make} {self.model}")  #Output prints the car's information in the format 'Year Make Model'.

# Task 2
# Create an instance of the Car class with the following attributes and call describe_car method:
# - Make: Toyota, Model: Corolla, Year: 2020

#Answers:
my_car_make = Car('Toyota', 'Corolla', 2020)            #Creating an instance of the Car class with the specified attributes
my_car_make.describe_car()                              #Calling the describe_car method to print the car's information

class Car:                                              #Class Definition: The Car class is defined with an __init__ method that
    def __init__(self, make, model, year):              #initializes the Car object with the attributes make, model, and year.

        self.make = make                                #Attributes Initialization: In the __init__ method, the parameters make, model, and year are assigned to the
        self.model = model                              #instance attributes self.make, self.model, and self.year, respectively.
        self.year = year                                #parameter make: The manufacturer of the car (e.g., 'BYD').
                                                        #paramerter model: The model of the car (e.g., 'Denzel 9').
                                                        #parameter year: The year the car was manufactured (e.g., 2024).

    def describe_car(self):                             #Method describe_car: This method prints the car's details in the format "Year Make Model" using an f-string for formatting.​
        print(f"{self.year} {self.make} {self.model}")  #Output prints the car's information in the format 'Year Make Model'.